### ISSUE TITLE
Transfer 0 error

### ISSUE THREAD

**Issue by ghost** [askmish/sawtooth-simplewallet#4] opened 2018-05-10 08:19 UTC
I tried the following command "simplewallet transfer 0 <user 1> <user 2>" and there was something like an infinite loop. This was the error that was displayed. 

simplewallet-processor    | SimpleWalletApplicator::Apply
simplewallet-processor    | Got: transfer and 0
simplewallet-processor    | Got beneficiary: 023e1bde5961655a5c3a51daab5e5820556fadd722932d7dd3eee38ecbc0ab2f94
simplewallet-processor    | 124360 [0x7faca6499780] DEBUG simplewallet null - SimpleWalletApplicator::doTransfer Key: 020ec936c18ed8d96272e8c62f5269db1122656ca0e9a894d37c8005a5a7c632f5 Address: 7e26646cb200282575bc2638258e663febd8ffcf543f0690bd2dc8da494d4bd2e6bac3
simplewallet-processor    | 124361 [0x7faca6499780] DEBUG simplewallet null - SimpleWalletApplicator::doTransfer Beneficiary Key: 023e1bde5961655a5c3a51daab5e5820556fadd722932d7dd3eee38ecbc0ab2f94 Address: 7e2664e728c0be707e30c78292c546be8be02442d70e6e0597c5e2b0ec77505b221589
simplewallet-processor    | 124363 [0x7faca1de9700] DEBUG sawtooth.MessageDispatcher null - ReceiveMessage MessageType: 8
simplewallet-processor    | 124364 [0x7faca6499780] ERROR sawtooth.TransactionProcessor null - applicator->Apply unknown error
simplewallet-processor    | 124365 [0x7faca1de9700] DEBUG sawtooth.MessageDispatcher null - ReceiveMessage MessageType: 5

**Comment by askmish** [comment] 2018-05-21 08:27
I have addressed the bug as much as possible in the simplewallet code, but the issue is deeper in the C++ SDK. Filed a JIRA bug here: https://jira.hyperledger.org/browse/STL-1249

The fix in C++ SDK will automatically fix bug in simplewallet.

LMK if I can go ahead and close this.

**Comment by ghost** [comment] 2018-05-21 09:31
Go for it! Thanks for the update Askmish 👍

**Comment by askmish** [comment] 2018-05-22 06:22
Thanks. :)

**Closed as completed by askmish** 2018-05-22 06:22 UTC
